eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

management.endpoints.web.exposure.include=health,metrics,prometheus,circuitbreakers
management.endpoint.health.show-details=always

management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.propagation.type=w3c

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

spring.reactor.context-propagation=AUTO

# For Logs
logging.file.path=/app/logs
logging.file.name=ProdApiGateway
logging.app.name=${spring.application.name}

# JWT Key
app.jwtSecret=X5+JS4JL8JFv18AeEnlc4eiT0y5Ea8Q72Q/kJpcUVNM=

# Allow all origins and common HTTP methods for all routes (CORS)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-origins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-methods=GET,POST,PUT,DELETE

# Redis Configuration
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# Rate Limiter Custom Settings
ratelimiter.enabled=false
ratelimiter.max-requests=10
ratelimiter.window-seconds=60
ratelimiter.fail-open.enabled=true

# Rate Limit Permanent Blocking Settings
permanent.blocking.enabled=true
permanent.blocking.violation-threshold=5
permanent.blocking.window-minutes=10
permanent.blocking.block-duration-days=30

## For HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Talent_123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=jetty

## Swagger route for Authentication Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[0].id=authentication-swagger
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/v3/api-docs
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=3

## Routes for Authentication Service
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/auth/**,/api/v1/test/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Registration Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[2].id=registration-swagger
spring.cloud.gateway.server.webflux.routes[2].uri=lb://registration-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/registration/v3/api-docs
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=3

## Routes for Registration Service
spring.cloud.gateway.server.webflux.routes[3].id=registration-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://registration-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/registration/**,/api/v1/onboarding/**
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Token Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[4].id=token-swagger
spring.cloud.gateway.server.webflux.routes[4].uri=lb://token-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/token/v3/api-docs
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=3

## Routes for Token Service
spring.cloud.gateway.server.webflux.routes[5].id=token-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://token-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/token/**
spring.cloud.gateway.server.webflux.routes[5].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[5].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[5].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Product Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[6].id=product-swagger
spring.cloud.gateway.server.webflux.routes[6].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/products/v3/api-docs
spring.cloud.gateway.server.webflux.routes[6].filters[0]=StripPrefix=3

## Routes for Product Service
spring.cloud.gateway.server.webflux.routes[7].id=product-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/products/**
spring.cloud.gateway.server.webflux.routes[7].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[7].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[7].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Order Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[8].id=order-swagger
spring.cloud.gateway.server.webflux.routes[8].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/order/v3/api-docs
spring.cloud.gateway.server.webflux.routes[8].filters[0]=StripPrefix=3

## Routes for Order Service
spring.cloud.gateway.server.webflux.routes[9].id=order-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/order/**
spring.cloud.gateway.server.webflux.routes[9].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[9].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[9].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Orchestrator Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[10].id=orchestrator-swagger
spring.cloud.gateway.server.webflux.routes[10].uri=lb://orchestrator-service
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/v1/orchestrator/v3/api-docs
spring.cloud.gateway.server.webflux.routes[10].filters[0]=StripPrefix=3

## Routes for Orchestrator Service
spring.cloud.gateway.server.webflux.routes[11].id=orchestrator-service
spring.cloud.gateway.server.webflux.routes[11].uri=lb://orchestrator-service
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/v1/orchestrator/**
spring.cloud.gateway.server.webflux.routes[11].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[11].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[11].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Stock Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[12].id=stock-swagger
spring.cloud.gateway.server.webflux.routes[12].uri=lb://stock-service
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/v1/inventories/v3/api-docs
spring.cloud.gateway.server.webflux.routes[12].filters[0]=StripPrefix=3

## Routes for Stock Service
spring.cloud.gateway.server.webflux.routes[13].id=stock-service
spring.cloud.gateway.server.webflux.routes[13].uri=lb://stock-service
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/api/v1/inventories/**
spring.cloud.gateway.server.webflux.routes[13].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[13].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[13].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Payment Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[14].id=payment-swagger
spring.cloud.gateway.server.webflux.routes[14].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/api/v1/payment/v3/api-docs
spring.cloud.gateway.server.webflux.routes[14].filters[0]=StripPrefix=3

## Routes for Payment Service
spring.cloud.gateway.server.webflux.routes[15].id=payment-service
spring.cloud.gateway.server.webflux.routes[15].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/api/v1/payment/**
spring.cloud.gateway.server.webflux.routes[15].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[15].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[15].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger route for Shipment Service (NO rate limiting)
spring.cloud.gateway.server.webflux.routes[16].id=shipment-swagger
spring.cloud.gateway.server.webflux.routes[16].uri=lb://shipment-service
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/api/v1/shipment/v3/api-docs
spring.cloud.gateway.server.webflux.routes[16].filters[0]=StripPrefix=3

## Routes for Shipment Service
spring.cloud.gateway.server.webflux.routes[17].id=shipment-service
spring.cloud.gateway.server.webflux.routes[17].uri=lb://shipment-service
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/api/v1/shipment/**
spring.cloud.gateway.server.webflux.routes[17].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[17].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[17].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Swagger aggregation
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/api/v1/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=registration-service
springdoc.swagger-ui.urls[1].url=/api/v1/registration/v3/api-docs

springdoc.swagger-ui.urls[2].name=token-service
springdoc.swagger-ui.urls[2].url=/api/v1/token/v3/api-docs

springdoc.swagger-ui.urls[3].name=product-service
springdoc.swagger-ui.urls[3].url=/api/v1/products/v3/api-docs

springdoc.swagger-ui.urls[4].name=order-service
springdoc.swagger-ui.urls[4].url=/api/v1/order/v3/api-docs

springdoc.swagger-ui.urls[5].name=orchestrator-service
springdoc.swagger-ui.urls[5].url=/api/v1/orchestrator/v3/api-docs

springdoc.swagger-ui.urls[6].name=stock-service
springdoc.swagger-ui.urls[6].url=/api/v1/inventories/v3/api-docs

springdoc.swagger-ui.urls[7].name=payment-service
springdoc.swagger-ui.urls[7].url=/api/v1/payment/v3/api-docs

springdoc.swagger-ui.urls[8].name=shipment-service
springdoc.swagger-ui.urls[8].url=/api/v1/shipment/v3/api-docs

## Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=true