eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

management.endpoints.web.exposure.include=*

management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.propagation.type=w3c

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

spring.reactor.context-propagation=AUTO

# For Logs
logging.file.path=/app/logs
logging.file.name=ApiGateway
logging.pattern.level=%5p [${spring.application.name:-},%X{traceId},%X{spanId}]

# JWT Key
app.jwtSecret=X5+JS4JL8JFv18AeEnlc4eiT0y5Ea8Q72Q/kJpcUVNM=

# Allow all origins and common HTTP methods for all routes (CORS)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-origins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowed-methods=GET,POST,PUT,DELETE

# Redis Configuration
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# Rate Limiter Custom Settings
ratelimiter.enabled=false
ratelimiter.max-requests=10
ratelimiter.window-seconds=60
ratelimiter.fail-open.enabled=true

# Rate Limit Permanent Blocking Settings
permanent.blocking.enabled=true
permanent.blocking.violation-threshold=5
permanent.blocking.window-minutes=10
permanent.blocking.block-duration-days=30

# For Redis Sentinel
#spring.redis.sentinel.master=mymaster
#spring.redis.sentinel.nodes=redis-host1:26379,redis-host2:26379,redis-host3:26379
#spring.redis.password=yourpassword
#spring.redis.timeout=5000

# For Redis Cluster
#spring.redis.cluster.nodes=redis-host1:6379,redis-host2:6379,redis-host3:6379
#spring.redis.password=yourpassword
#spring.redis.timeout=5000

## Routes for Payment Service
spring.cloud.gateway.server.webflux.routes[0].id=payment-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/payment/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Routes for Token Service
spring.cloud.gateway.server.webflux.routes[1].id=token-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://token-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/token/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Routes for Registration Service
spring.cloud.gateway.server.webflux.routes[2].id=registration-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://registration-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/registration/**,/api/v1/onboarding/**
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Routes for Authentication Service
spring.cloud.gateway.server.webflux.routes[3].id=auth-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/auth/**,/api/v1/test/**
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Routes for Order Service
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/order/**
spring.cloud.gateway.server.webflux.routes[4].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[4].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[4].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}

## Routes for Product Service
spring.cloud.gateway.server.webflux.routes[5].id=product-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/products/**
spring.cloud.gateway.server.webflux.routes[5].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[5].filters[0].args.rate-limiter=#{@customUserRateLimiter}
spring.cloud.gateway.server.webflux.routes[5].filters[0].args.key-resolver=#{@userIdOrIpKeyResolver}
