spring.boot.message=Authentication Service

# R2DBC & Pool Settings
spring.r2dbc.url=r2dbc:pool:mariadb://mariadb:3306/auth_db?initialSize=5&maxSize=20&maxIdleTime=PT30M&validationQuery=SELECT%201
spring.r2dbc.username=root
spring.r2dbc.password=root

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

management.endpoints.web.exposure.include=*

management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.propagation.type=w3c

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# For Logs
logging.file.path=/app/logs
logging.file.name=Authentication
logging.pattern.level=%5p [${spring.application.name:-},%X{traceId},%X{spanId}]

spring.messages.basename=ValidationMessages

spring.reactor.context-propagation=AUTO

# JWT settings
app.jwtSecret=X5+JS4JL8JFv18AeEnlc4eiT0y5Ea8Q72Q/kJpcUVNM=
app.jwtExpirationMs=86400000