spring.boot.message=Stock Service

# R2DBC & Pool Settings
spring.r2dbc.url=r2dbc:pool:mariadb://mariadb:3306/stock_db?initialSize=5&maxSize=20&maxIdleTime=PT30M&validationQuery=SELECT%201
spring.r2dbc.username=root
spring.r2dbc.password=root

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

management.endpoints.web.exposure.include=*

management.tracing.sampling.probability=1.0
management.tracing.enabled=true
management.tracing.propagation.type=w3c

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# For Logs
logging.file.path=/app/logs
logging.file.name=ProdStockService
logging.pattern.level=%5p [${spring.application.name:-},%X{traceId},%X{spanId}]

spring.messages.basename=ValidationMessages

spring.reactor.context-propagation=AUTO
#################################################################################################

# Kafka Topic Names
spring.kafka.topic.name=order_topics
spring.kafka.reply-topic=order_orchestrator_topics
spring.kafka.dlq-topic=stock_dlq

# Kafka Consumer Configs
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=stock
spring.kafka.consumer.auto-offset-reset=latest

# Kafka Producer Configs
spring.kafka.producer.bootstrap-servers=localhost:9092

# Retry and DLQ config
app.stock.max-retries=3
app.stock.retry-backoff-ms=2000
app.consumer.shutdown-wait-ms=30000